### ISSUE TITLE
Characters list issues when using tablet view

### ISSUE THREAD

**Issue by bartdebever** [FightCore/Frontend#31]
The game series and the game chip have visual issues when using the tablet view.

**Comment by Frannsoft** [comment]
Could you describe the 'visual issue' a bit more? Some screenshots of what it currently looks liks versus what it should look like would be super helpful : )

**Comment by bartdebever** [comment]
On Google Chrome, opening the website's character page on the Character screen using the IPad pro view, the following result happens:

![image](https://user-images.githubusercontent.com/11806849/67146217-3da25180-f289-11e9-8573-ce2f99000bc9.png)

The tag name is not of the greatest concern as they will be reworked at some stage in the project.
The game series icon should not fall outside of the card.

**Comment by Frannsoft** [comment]
It looks like a `mat-chip-list` component is being used, but there's no loop creating `mat-chip` components inside the list. Should the list component stay? Just wondering since it'll affect a fix for the styling issue.

**Comment by bartdebever** [comment]
I'm pretty sure I made it that way because the `mat-chip-list` was required for the `mat-chip` to show up. I might be completely wrong on that. Honestly go for whatever you feel is right, could be an entire rework and I would be fine with that.
